# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 311138dc010e5ecb97d9abde38dd77b4bc7ad33c92dba847ab613f3283909aaebf068bf669b396c039a68a2e4eca4ad376b3020c10edd9bac2d66f4c87e9a000

test:
  secret_key_base: 9e31f1efd6afc6e8fc8b9d200e9973c478e632e880b0b5b609ac1871c826a41a0c234fd5dc87f439d934d0c32bf78aa77ba379f84a2b463282456d62c23008f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
